on:
  pull_request:
    paths:
      - ".github/workflows/test-prepare-runner.yml"
      - "prepare-runner/**"
  push:
    branches: [main]
    paths:
      - ".github/workflows/test-prepare-runner.yml"
      - "prepare-runner/**"
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *"

jobs:
  test-prepare-runner:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos15
          - os: macos15
          - os: macos15
          - os: macos15
          - os: macos15

    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container != '' && fromJson(matrix.container) || null }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Run prepare-runner action
        uses: ./prepare-runner
        with:
          enable_ccache: false

      - name: Verify ccache is disabled
        shell: bash
        run: |
          if [ "$CCACHE_DISABLE" != "1" ]; then
            echo "CCACHE_DISABLE is not set to 1"
            exit 1
          fi
          echo "CCACHE_DISABLE is correctly set to 1"

      - name: Verify build tools are able to run
        shell: bash
        run: |
          cmake --version
          conan --version
          ccache --version
          # Rust is not installed in the Clio CI image.
          if [[ ! "${{ matrix.container }}" =~ ghcr.io/xrplf/clio-ci ]]; then
            rustc --version
          fi

          if [[ "${{ matrix.os }}" == "macos15" ]]; then
            colima --version
            docker --version
          fi
